In [10]:
import numpy as np
from numpy import linalg as LA

m, n = 4, 3
A = np.random.rand(m, n)
U, S, V = LA.svd(A)
print(U)

# checking if U, V are orthogonal and S is a diagonal matrix with
# nonnegative decreasing elements
print('Frobenius norm of (UU^T - I) =', \
    LA.norm(U.dot(U.T) - np.eye(m)))
print('\n S = ', S, '\n')
print('Frobenius norm of (VV^T - I) =', \
    LA.norm(V.dot(V.T) - np.eye(n)))

[[-0.62059443  0.58633908 -0.49921665 -0.14782345]
 [-0.38584227  0.31546399  0.86542244 -0.05149966]
 [-0.53999718 -0.70040738 -0.01320397 -0.46653854]
 [-0.41760189 -0.2571351  -0.04064968  0.8705388 ]]
Frobenius norm of (UU^T - I) = 1.4910288095027898e-15

 S =  [2.14379378 0.61718434 0.29378574] 

Frobenius norm of (VV^T - I) = 1.186123852934062e-15
